// Real, Mothership-native health reporting - replaces the health-report.yml
// PR #1 deleted, which was a non-functional copy-paste from tso (referenced
// scripts/health-analyzer.js and Prisma, neither of which exist in this
// repo, and posted comments literally saying "Auto-generated by TSO Health
// System"). This one reports on the hub/swarm's own health, not a spoke's.
//
// Runs as a plain GitHub Actions script (no AI, no Vercel call) - like
// prune-logs.js, it only needs a GitHub token, mirrored as the
// GLOBAL_GITHUB_TOKEN Actions secret on this repo.
//
// Multi-tenancy: each spoke's own data (issues filed, decision log) is read
// using ITS tenant's own resolved credential when octokitFactory is
// supplied (decision #1 in lessons.md's multi-tenancy entry) - falls back
// to the single `octokit` passed to buildFullReport when octokitFactory
// isn't given, so existing single-tenant callers/tests keep working
// unchanged. The report itself (and the pinned issue it publishes to) stay
// hub-wide/operator-facing - this is about using the right credential to
// read each spoke, not about splitting the report per tenant.
//
// Usage: node scripts/health-report.js

import { Octokit } from '@octokit/rest';
import { loadSpokesRegistry, loadTenantsRegistry, resolveTenantIdForSpoke, findTenant, resolveSecretRef } from '../lib/secrets.js';

const DECISION_LOG_PATH = 'ai_decision_log.json';
const HUB_ISSUE_LABEL = 'cto-hub-auto';
const REPORT_ISSUE_LABEL = 'mothership-health-report';
const REPORT_ISSUE_TITLE = 'Mothership Health Report';
const REPORT_WINDOW_DAYS = 7;

const HUB_OWNER = process.env.HUB_GITHUB_OWNER || 'adamberneche-afk';
const HUB_REPO = process.env.HUB_GITHUB_REPO || 'Mothership';

// loadSpokesRegistry/loadTenantsRegistry/resolveTenantIdForSpoke/findTenant/
// resolveSecretRef now live in ../lib/secrets.js (imported above) - deduped
// out of what used to be 6 byte-identical Node-side copies of the same
// functions, see that file's header comment.

async function safeGetTextContent(octokit, owner, repo, path) {
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path });
    return Buffer.from(data.content, 'base64').toString('utf8');
  } catch (e) {
    return null;
  }
}

function safeParseJsonArray(text) {
  if (!text) return [];
  try {
    const parsed = JSON.parse(text);
    return Array.isArray(parsed) ? parsed : [];
  } catch (e) {
    return [];
  }
}

function groupBy(arr, keyFn) {
  const out = {};
  for (const item of arr) {
    const k = keyFn(item);
    (out[k] = out[k] || []).push(item);
  }
  return out;
}

async function countIssuesCreatedSince(octokit, owner, repo, windowStart) {
  const { data } = await octokit.issues.listForRepo({
    owner, repo, state: 'all', labels: HUB_ISSUE_LABEL, sort: 'created', direction: 'desc', per_page: 100
  });
  let count = 0;
  for (const issue of data) {
    if (new Date(issue.created_at) < windowStart) break;
    count++;
  }
  return count;
}

// Builds the report for a single spoke. Exported separately from
// buildFullReport so tests can drive it directly without needing a real
// spokes.json on disk.
export async function buildReportForSpoke(octokit, spoke, { windowStart }) {
  const issuesFiled = await countIssuesCreatedSince(octokit, spoke.owner, spoke.repo, windowStart);
  const logText = await safeGetTextContent(octokit, spoke.owner, spoke.repo, DECISION_LOG_PATH);
  const allEntries = safeParseJsonArray(logText);
  const recentEntries = allEntries.filter((e) => e && e.timestamp && new Date(e.timestamp) >= windowStart);

  const byOutcomeGroups = groupBy(recentEntries, (e) => e.outcome || 'unknown');
  const byOutcome = Object.fromEntries(Object.entries(byOutcomeGroups).map(([k, v]) => [k, v.length]));
  const total = recentEntries.length;
  const createdCount = byOutcome.created || 0;
  const dryRunFindingCount = byOutcome.dry_run_would_create || 0;
  const skipRate = total > 0 ? 1 - createdCount / total : null;

  // Live/dry-run status is INFERRED from observed decision-log outcomes,
  // not read from Vercel config - a GitHub Actions runner has no way to
  // read the hub's Vercel env vars directly.
  let capabilityStatus;
  if (total === 0) {
    capabilityStatus = 'no decisions logged this window (heartbeat may not have run, or spoke was recently added)';
  } else if (createdCount > 0) {
    capabilityStatus = 'live (created at least one issue this window)';
  } else if (dryRunFindingCount > 0) {
    capabilityStatus = 'dry-run (reported findings, filed nothing)';
  } else {
    capabilityStatus = 'active, no real findings this window';
  }

  return { owner: spoke.owner, repo: spoke.repo, issuesFiled, entriesInWindow: total, byOutcome, skipRate, capabilityStatus };
}

export async function buildFullReport(octokit, { now = Date.now(), windowDays = REPORT_WINDOW_DAYS, octokitFactory, spokesOverride, tenantsOverride } = {}) {
  const spokes = spokesOverride || loadSpokesRegistry();
  const tenants = tenantsOverride || loadTenantsRegistry();
  const windowStart = new Date(now - windowDays * 24 * 60 * 60 * 1000);
  const generatedAt = new Date(now).toISOString();

  // Read-only diagnostic tool - best-effort-with-some-token is the right
  // behavior here (matches doctor.js/prune-logs.js/collect-issue-feedback.js's
  // identical, deliberate fallback), unlike the hard-skip rule in
  // api/autonomous_agent.js/api/recursive_learning.js.
  const resolveOctokitForSpoke = async (spoke) => {
    if (!octokitFactory) return octokit;
    const tenantId = resolveTenantIdForSpoke(spoke.owner, spoke.repo, spokes);
    const tenant = findTenant(tenantId, tenants);
    const resolved = tenant ? await resolveSecretRef(tenant.githubCredentialRef) : null;
    const token = resolved || process.env.GLOBAL_GITHUB_TOKEN;
    return octokitFactory(token);
  };

  const spokeReports = [];
  for (const spoke of spokes) {
    try {
      spokeReports.push(await buildReportForSpoke(await resolveOctokitForSpoke(spoke), spoke, { windowStart }));
    } catch (e) {
      spokeReports.push({ owner: spoke.owner, repo: spoke.repo, error: e.message });
    }
  }

  return { generatedAt, windowDays, spokes: spokeReports };
}

export function renderReportMarkdown(report) {
  const lines = [];
  lines.push('# Mothership Health Report');
  lines.push('');
  lines.push(`Generated: ${report.generatedAt} · Window: last ${report.windowDays} days`);
  lines.push('');

  if (report.spokes.length === 0) {
    lines.push('_No spokes registered in `spokes.json` yet - nothing to report on._');
    return lines.join('\n');
  }

  lines.push('| Spoke | Issues Filed | Decisions Logged | Skip Rate | Status |');
  lines.push('|---|---|---|---|---|');
  for (const s of report.spokes) {
    if (s.error) {
      lines.push(`| ${s.owner}/${s.repo} | - | - | - | error: ${s.error} |`);
      continue;
    }
    const skipRatePct = s.skipRate === null ? 'n/a' : `${Math.round(s.skipRate * 100)}%`;
    lines.push(`| ${s.owner}/${s.repo} | ${s.issuesFiled} | ${s.entriesInWindow} | ${skipRatePct} | ${s.capabilityStatus} |`);
  }

  lines.push('');
  lines.push('<details><summary>Outcome breakdown per spoke</summary>');
  lines.push('');
  for (const s of report.spokes) {
    if (s.error) continue;
    lines.push(`- **${s.owner}/${s.repo}**: ${JSON.stringify(s.byOutcome)}`);
  }
  lines.push('');
  lines.push('</details>');

  return lines.join('\n');
}

async function findExistingReportIssue(octokit) {
  const { data } = await octokit.issues.listForRepo({
    owner: HUB_OWNER, repo: HUB_REPO, state: 'all', labels: REPORT_ISSUE_LABEL, per_page: 10
  });
  return data.find((issue) => issue.title === REPORT_ISSUE_TITLE) || null;
}

// Updates the same pinned issue in place on every run instead of creating a
// new one each time - a deliberate callback to the original issue-spam
// disaster this whole system exists to avoid repeating. Always uses the
// hub's own credential (never a tenant-scoped one) - this issue lives on
// the hub repo itself.
export async function publishReport(octokit, body) {
  const existing = await findExistingReportIssue(octokit);
  if (existing) {
    const updateParams = { owner: HUB_OWNER, repo: HUB_REPO, issue_number: existing.number, body };
    // If a human closed the report issue (e.g. tidying notifications), the
    // update itself doesn't reopen it by default - reopen explicitly, or
    // every future run would keep silently rewriting a closed issue's body
    // instead of surfacing anywhere a maintainer would actually look.
    const wasClosed = existing.state === 'closed';
    if (wasClosed) updateParams.state = 'open';
    await octokit.issues.update(updateParams);
    return { action: wasClosed ? 'reopened' : 'updated', issueUrl: existing.html_url };
  }
  const created = await octokit.issues.create({
    owner: HUB_OWNER, repo: HUB_REPO, title: REPORT_ISSUE_TITLE, body, labels: [REPORT_ISSUE_LABEL]
  });
  return { action: 'created', issueUrl: created.data.html_url };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const octokit = new Octokit({ auth: process.env.GLOBAL_GITHUB_TOKEN });
  const octokitFactory = (token) => new Octokit({ auth: token });

  buildFullReport(octokit, { octokitFactory })
    .then(async (report) => {
      const body = renderReportMarkdown(report);
      console.log(body);
      const result = await publishReport(octokit, body);
      console.log(JSON.stringify(result));
    })
    .catch((err) => {
      console.error(err);
      process.exitCode = 1;
    });
}
